#!/bin/sh

kubectl config set-cluster default-cluster --server=$KUBE_URL --certificate-authority="$KUBE_CA_PEM_FILE"
kubectl config set-credentials default-admin --token=$KUBE_TOKEN
kubectl config set-context default-system --cluster=default-cluster --user=default-admin --namespace $KUBE_NAMESPACE
kubectl config use-context default-system
